version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8081

functions:
  process-sensor-data:
    lang: python3-http
    handler: ./process-sensor-data
    image: ghcr.io/teddydore11780/process-sensor-data:latest
