services:
  mosquitto:
    build:
      context: ./mqtt
    container_name: edgefusion-mqtt
    ports:
      - "1883:1883"
    volumes:
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log
    restart: unless-stopped

  gateway:
    build:
      context: ./gateway
    container_name: edgefusion-gateway
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MQTT_BROKER_URL: mqtt://mosquitto:1883
      SENSOR_TOPIC: sensor/data
      DATABASE_NAME: edgefusion.db
      LOG_LEVEL: INFO
      OPENFAAS_FUNCTION_URL: http://k3d-edgefusion-server-0:31112/function/process-sensor-data
    volumes:
      - ./gateway/database:/app/database
    depends_on:
      - mosquitto
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - k3d-edgefusion
    restart: unless-stopped

  dashboard:
    build:
      context: ./dashboard
    container_name: edgefusion-dashboard
    ports:
      - "5173:80"
    depends_on:
      - gateway
    restart: unless-stopped

volumes:
  mqtt-data:
  mqtt-log:

networks:
  k3d-edgefusion:
    external: true
    name: k3d-edgefusion