import { useEffect, useState } from "react";
import PageHeader from "../components/layout/PageHeader";
import { getAlerts } from "../services/api";
import socket from "../services/socket";

export default function Alerts() {
    const [alerts, setAlerts] = useState([]);
    const [loading, setLoading] = useState(true);

    async function loadAlerts() {
        try {
            const response = await getAlerts();
            setAlerts(Array.isArray(response) ? response : response.data || []);
        } catch (error) {
            console.error("Alerts load error:", error.message);
        } finally {
            setLoading(false);
        }
    }

    useEffect(() => {
        loadAlerts();

        socket.on("alert:created", (alert) => {
            console.log("LIVE ALERT RECEIVED:", alert);

            setAlerts((currentAlerts) => [
                {
                    ...alert,
                    id: alert.id || `live-${Date.now()}`
                },
                ...currentAlerts
            ]);
        });

        return () => {
            socket.off("alert:created");
        };
    }, []);

    if (loading) {
        return (
            <section className="page">
                <h2>Loading Alerts...</h2>
            </section>
        );
    }

    return (
        <section className="page">
            <PageHeader
                title="Alert Centre"
                subtitle="Critical events generated by the EdgeFusion serverless processing pipeline."
            />

            <div className="table-card">
                <table>
                    <thead>
                        <tr>
                            <th>Device</th>
                            <th>Alert Type</th>
                            <th>Severity</th>
                            <th>Message</th>
                            <th>Created At</th>
                        </tr>
                    </thead>

                    <tbody>
                        {alerts.length > 0 ? (
                            alerts.map((alert) => (
                                <tr key={alert.id}>
                                    <td>{alert.deviceId}</td>
                                    <td>{alert.alertType}</td>
                                    <td>
                                        <span className="badge danger">
                                            {alert.severity}
                                        </span>
                                    </td>
                                    <td>{alert.message}</td>
                                    <td>{alert.createdAt}</td>
                                </tr>
                            ))
                        ) : (
                            <tr>
                                <td colSpan="5" className="empty-table">
                                    No alerts available.
                                </td>
                            </tr>
                        )}
                    </tbody>
                </table>
            </div>
        </section>
    );
}
